### PR TITLE
Sensor class dk

### PR DESCRIPTION
**Pull request by davidkyle210**
Hey Benjamin, I am trying to learn how to use the github desktop app. I added a new class that my drc code will rely on. It is a representation of a met mast sensor as a python object--useful for transforming sensors between different forms (i.e. string, tuple) and useful for selecting columns from the multi-index met mast pandas dataframes.

### CODE REVIEW

**Comment by bkandel-edf** [comment]
David, a few things you want to consider to update before we merge: the orientation can also have value "SM", a specific value for Stub Mounted sensors (i.e. mounted on a vertical boom at top of the tower). Also, is the sector sufficient for what you are trying to accomplish with that class? The sensor name contains only the sector, but the precise orientation comes from the metadata in the sensor tables (for M2D2 sensors)... Finally, sensor names can optionally have a letter at the end (to differentiate sensors that would otherwise have the same name but that we want to see as 2 different columns). Ex: SPD_80_NW_A. I should probably update WRAM with that information...

**Comment by davidkyle210** [comment]
I can make some changes to the class. Specifically

- allowing 'SM' value for the orient attribute
- adding an optional attribute, orient_angle, to the class so that, if known, the Sensor can have information for the precise orientation
- adding an optional attribute, tag, to the class so that sensors can be distinguished even if they have the same type, orientation, etc.
- updating documentation with these changes
- updating tests with these changes

I'll get back to you with a new pull request today.

**Comment by davidkyle210** [comment]
Alright Benjamin, I made the changes listed in my last comment.
Let me know if you have any other suggested changes

**Comment by bkandel-edf** [comment]
As discussed, closing the pull request without merging to work on the new repo.

**Pull request closed without merging**
